class Perfect_present
  def result

    recipient =
       {:small_child => {:male =>
                         {:blood_relative =>
                                  {:under_50 =>
                                        {:toys => "http://www.toysrus.com/graphics/product_images/pTRU1-20692668dt.jpg",
                                        :sports => "http://mommifried.com/wp-content/uploads/2014/10/Smart-Shots-Sports-Center.jpg",
                                        :nature => "http://www.growingtreetoys.com/img/cache/product/011661__.jpg",
                                        :music => "https://pbs.twimg.com/profile_images/605742859963101186/JVS7Kvuq.jpg",
                                        :art => "http://ecx.images-amazon.com/images/I/81ToA48TLPL._SL1500_.jpg",
                                        :electronics => "http://i.ebayimg.com/00/s/MTQ1M1gxNjAw/z/8jsAAOSwDNdVjKtG/$_35.JPG"}},
                                  {:under_100 =>
                                        {:toys => "www.toysrus.com/graphics/product_images/pTRU1-16655104enh-z6.jpg",
                                        :sports => "http://www.toysrus.com/graphics/product_images/pTRU1-17512608dt.jpg",
                                        :nature => "http://ecx.images-amazon.com/images/I/71oaD0HH5IL._SL1000_.jpg",
                                        :music => "http://ecx.images-amazon.com/images/I/51EVS6F8-qL._SY355_.jpg",
                                        :art => "http://happyhourprojects.com/wp-content/uploads/2013/09/Step2creative-art-studio-giveaway.jpg",
                                        :electronics => "http://www.toysrus.com/graphics/product_images/pTRU1-18508780dt.jpg"}},
                                 {:over_100 =>
                                        {:toys => "http://www.1800trampoline.com/images/products/detail/410201335031PM.jpg",
                                        :sports => "http://ecx.images-amazon.com/images/I/919gDg-3iJL._SL1500_.jpg",
                                        :nature => "http://www.creativityinstitute.com/images/products/detail/G97030_Modular_Science_kid3.jpg",
                                        :music => "http://ak1.ostkcdn.com/images/products/9531378/Berry-Toys-Complete-Kids-Large-Drum-Set-with-Cymbal-Stool-and-Sticks-fadcae7e-0092-419d-9727-326c6ed49bad_600.jpg",
                                        :art => "http://www.alextoys.com/wp-content/uploads/sites/2/2013/09/1_A-1024x1019.jpg",
                                        :electronics => "http://c.shld.net/rpx/i/s/i/spin/10112611/prod_1484219212?hei=333&wid=333&op_sharpen=1"}}},
                         {:extended_family =>
                                 {:under_50 =>
                                        {:toys => "http://www.toysrus.com/graphics/product_images/pTRU1-20692668dt.jpg",
                                        :sports => "http://mommifried.com/wp-content/uploads/2014/10/Smart-Shots-Sports-Center.jpg",
                                        :nature => "http://www.growingtreetoys.com/img/cache/product/011661__.jpg",
                                        :music => "https://pbs.twimg.com/profile_images/605742859963101186/JVS7Kvuq.jpg",
                                        :art => "http://ecx.images-amazon.com/images/I/81ToA48TLPL._SL1500_.jpg",
                                        :electronics => "http://i.ebayimg.com/00/s/MTQ1M1gxNjAw/z/8jsAAOSwDNdVjKtG/$_35.JPG"}},
                                 {:under_100 =>
                                        {:toys => "www.toysrus.com/graphics/product_images/pTRU1-16655104enh-z6.jpg",
                                        :sports => "http://www.toysrus.com/graphics/product_images/pTRU1-17512608dt.jpg"
                                        :nature => "http://ecx.images-amazon.com/images/I/71oaD0HH5IL._SL1000_.jpg",
                                        :music => "http://ecx.images-amazon.com/images/I/51EVS6F8-qL._SY355_.jpg",
                                        :art => "http://happyhourprojects.com/wp-content/uploads/2013/09/Step2creative-art-studio-giveaway.jpg",
                                       :electronics => "http://www.toysrus.com/graphics/product_images/pTRU1-18508780dt.jpg"}},
                                 {:over_100 =>
                                        {:toys => "http://www.1800trampoline.com/images/products/detail/410201335031PM.jpg",
                                        :sports => "http://ecx.images-amazon.com/images/I/919gDg-3iJL._SL1500_.jpg",
                                        :nature => "http://www.creativityinstitute.com/images/products/detail/G97030_Modular_Science_kid3.jpg",
                                        :music => "http://ak1.ostkcdn.com/images/products/9531378/Berry-Toys-Complete-Kids-Large-Drum-Set-with-Cymbal-Stool-and-Sticks-fadcae7e-0092-419d-9727-326c6ed49bad_600.jpg",
                                        :art => "http://www.alextoys.com/wp-content/uploads/sites/2/2013/09/1_A-1024x1019.jpg",
                                        :electronics => "http://c.shld.net/rpx/i/s/i/spin/10112611/prod_1484219212?hei=333&wid=333&op_sharpen=1"}}},
                         {:friend =>
                                {:under_50 =>
                                        {:toys => "http://www.toysrus.com/graphics/product_images/pTRU1-20692668dt.jpg",
                                        :sports => "http://mommifried.com/wp-content/uploads/2014/10/Smart-Shots-Sports-Center.jpg",
                                        :nature => "http://www.growingtreetoys.com/img/cache/product/011661__.jpg",
                                        :music => "https://pbs.twimg.com/profile_images/605742859963101186/JVS7Kvuq.jpg",
                                        :art => "http://ecx.images-amazon.com/images/I/81ToA48TLPL._SL1500_.jpg",
                                        :electronics => "http://i.ebayimg.com/00/s/MTQ1M1gxNjAw/z/8jsAAOSwDNdVjKtG/$_35.JPG"}},
                                {:under_100 =>
                                        {:toys => "www.toysrus.com/graphics/product_images/pTRU1-16655104enh-z6.jpg",
                                        :sports => "http://www.toysrus.com/graphics/product_images/pTRU1-17512608dt.jpg",
                                        :nature => "http://ecx.images-amazon.com/images/I/71oaD0HH5IL._SL1000_.jpg",
                                        :music => "http://ecx.images-amazon.com/images/I/51EVS6F8-qL._SY355_.jpg",
                                        :art => "http://happyhourprojects.com/wp-content/uploads/2013/09/Step2creative-art-studio-giveaway.jpg",
                                        :electronics => "http://www.toysrus.com/graphics/product_images/pTRU1-18508780dt.jpg"}},
                                {:over_100 =>
                                        {:toys => "http://www.1800trampoline.com/images/products/detail/410201335031PM.jpg",
                                        :sports => "http://ecx.images-amazon.com/images/I/919gDg-3iJL._SL1500_.jpg",
                                        :nature => "http://www.creativityinstitute.com/images/products/detail/G97030_Modular_Science_kid3.jpg",
                                        :music => "http://ak1.ostkcdn.com/images/products/9531378/Berry-Toys-Complete-Kids-Large-Drum-Set-with-Cymbal-Stool-and-Sticks-fadcae7e-0092-419d-9727-326c6ed49bad_600.jpg",
                                        :art => "http://www.alextoys.com/wp-content/uploads/sites/2/2013/09/1_A-1024x1019.jpg",
                                        :electronics => "http://c.shld.net/rpx/i/s/i/spin/10112611/prod_1484219212?hei=333&wid=333&op_sharpen=1"}}}},
               {:female =>
                           {:blood_relative =>
                                {:under_50 =>
                                        {:toys => "http://www.toysrus.com/graphics/product_images/pTRU1-18272325enh-z6.jpg",
                                        :sports => "http://ecx.images-amazon.com/images/I/716SKvjHfsL._SY355_.jpg",
                                        :nature => "http://www.growingtreetoys.com/img/cache/product/011661__.jpg",
                                        :music => "http://karaokeforall.com/wp-content/uploads/2014/02/Singing-Machine-SML283P.jpg",
                                        :art => "http://ecx.images-amazon.com/images/I/81ToA48TLPL._SL1500_.jpg",
                                        :electronics => "http://i.ebayimg.com/00/s/MTQ1M1gxNjAw/z/8jsAAOSwDNdVjKtG/$_35.JPG"}},
                               {:under_100 =>
                                               {:toys =>"http://i5.walmartimages.com/dfw/dce07b8c-8c50/k2-_457733b3-79bb-45d3-9cf3-043098069d20.v1.jpg" ,
                                               :sports => "http://www.toysrus.com/graphics/product_images/pTRU1-17512608dt.jpg",
                                               :nature => "http://ecx.images-amazon.com/images/I/71oaD0HH5IL._SL1000_.jpg",
                                               :music => "http://ecx.images-amazon.com/images/I/51EVS6F8-qL._SY355_.jpg",
                                               :art => "http://happyhourprojects.com/wp-content/uploads/2013/09/Step2creative-art-studio-giveaway.jpg",
                                               :electronics => "http://www.toysrus.com/graphics/product_images/pTRU1-18508780dt.jpg"}},
                                       {:over_100 =>
                                              {:toys => "http://www.1800trampoline.com/images/products/detail/410201335031PM.jpg",
                                              :sports => "http://trus.imageg.net/graphics/product_images/pTRU1-19164336reg.jpg",
                                              :nature => "http://www.creativityinstitute.com/images/products/detail/G97030_Modular_Science_kid3.jpg",
                                              :music => "http://ak1.ostkcdn.com/images/products/8915564/Union-3-piece-Pink-Toy-Drum-Set-P16133065.jpg",
                                              :art => "http://www.alextoys.com/wp-content/uploads/sites/2/2013/09/1_A-1024x1019.jpg",
                                              :electronics => "http://www.1800trampoline.com/images/products/detail/410201335031PM.jpg"}}},
                              {:extended_family =>
                                       {:under_50 =>
                                             {:toys => "http://www.toysrus.com/graphics/product_images/pTRU1-18272325enh-z6.jpg",
                                             :sports => "http://ecx.images-amazon.com/images/I/716SKvjHfsL._SY355_.jpg",
                                             :nature => "http://www.growingtreetoys.com/img/cache/product/011661__.jpg",
                                             :music => "http://karaokeforall.com/wp-content/uploads/2014/02/Singing-Machine-SML283P.jpg",
                                             :art => "http://ecx.images-amazon.com/images/I/81ToA48TLPL._SL1500_.jpg",
                                             :electronics => "http://i.ebayimg.com/00/s/MTQ1M1gxNjAw/z/8jsAAOSwDNdVjKtG/$_35.JPG"}},
                                       {:under_100 =>
                                               {:toys => "http://i5.walmartimages.com/dfw/dce07b8c-8c50/k2-_457733b3-79bb-45d3-9cf3-043098069d20.v1.jpg",
                                               :sports => "http://www.toysrus.com/graphics/product_images/pTRU1-17512608dt.jpg",
                                               :nature => "http://ecx.images-amazon.com/images/I/71oaD0HH5IL._SL1000_.jpg",
                                               :music => "http://ecx.images-amazon.com/images/I/51EVS6F8-qL._SY355_.jpg",
                                               :art => "http://happyhourprojects.com/wp-content/uploads/2013/09/Step2creative-art-studio-giveaway.jpg",
                                               :electronics => "http://www.toysrus.com/graphics/product_images/pTRU1-18508780dt.jpg"}},
                                       {:over_100 =>
                                               {:toys => "http://www.1800trampoline.com/images/products/detail/410201335031PM.jpg",
                                               :sports => "http://trus.imageg.net/graphics/product_images/pTRU1-19164336reg.jpg",
                                               :nature => "http://www.creativityinstitute.com/images/products/detail/G97030_Modular_Science_kid3.jpg",
                                              :music => "http://ak1.ostkcdn.com/images/products/8915564/Union-3-piece-Pink-Toy-Drum-Set-P16133065.jpg",
                                               :art => "http://www.alextoys.com/wp-content/uploads/sites/2/2013/09/1_A-1024x1019.jpg",
                                               :electronics => "http://c.shld.net/rpx/i/s/i/spin/10112611/prod_1484219212?hei=333&wid=333&op_sharpen=1"}}},
                                 {:friend =>
                                       {:under_50 =>
                                             {:toys => "http://www.toysrus.com/graphics/product_images/pTRU1-18272325enh-z6.jpg",
                                             :sports => "http://ecx.images-amazon.com/images/I/716SKvjHfsL._SY355_.jpg",
                                             :nature => "http://www.growingtreetoys.com/img/cache/product/011661__.jpg",
                                             :music => "http://karaokeforall.com/wp-content/uploads/2014/02/Singing-Machine-SML283P.jpg",
                                             :art => "http://ecx.images-amazon.com/images/I/81ToA48TLPL._SL1500_.jpg",
                                             :electronics => "http://i.ebayimg.com/00/s/MTQ1M1gxNjAw/z/8jsAAOSwDNdVjKtG/$_35.JPG"}},
                                       {:under_100 =>
                                               {:toys => "http://i5.walmartimages.com/dfw/dce07b8c-8c50/k2-_457733b3-79bb-45d3-9cf3-043098069d20.v1.jpg",
                                               :sports => "http://www.toysrus.com/graphics/product_images/pTRU1-17512608dt.jpg",
                                               :nature => "http://ecx.images-amazon.com/images/I/71oaD0HH5IL._SL1000_.jpg",
                                               :music => "http://ecx.images-amazon.com/images/I/51EVS6F8-qL._SY355_.jpg",
                                               :art => "http://happyhourprojects.com/wp-content/uploads/2013/09/Step2creative-art-studio-giveaway.jpg",
                                               :electronics => "http://www.toysrus.com/graphics/product_images/pTRU1-18508780dt.jpg"}},
                                       {:over_100 =>
                                               {:toys => "http://www.1800trampoline.com/images/products/detail/410201335031PM.jpg",
                                               :sports => "http://trus.imageg.net/graphics/product_images/pTRU1-19164336reg.jpg",
                                               :nature => "http://www.creativityinstitute.com/images/products/detail/G97030_Modular_Science_kid3.jpg",
                                               :music => "http://ak1.ostkcdn.com/images/products/8915564/Union-3-piece-Pink-Toy-Drum-Set-P16133065.jpg",
                                               :art => "http://www.alextoys.com/wp-content/uploads/sites/2/2013/09/1_A-1024x1019.jpg",
                                               :electronics => "http://c.shld.net/rpx/i/s/i/spin/10112611/prod_1484219212?hei=333&wid=333&op_sharpen=1"}}}},

    :teenager => {:male =>
                           {:significant_other =>
                                       {:under_50 =>
                                             {:sports => "http://ecx.images-amazon.com/images/I/812WyxHZm6L._SX425_.jpg",
                                             :nature => "Amscope Metal Body Kids Student Beginner Biological Microscope Kit",
                                             :music => "https://img0.etsystatic.com/062/0/8907796/il_570xN.791932066_4hpb.jpg",
                                             :art => "http://ecx.images-amazon.com/images/I/91KLFz-tGjL._SX355_.jpg",
                                             :romantic_gifts => "https://www.ediblearrangements.com/Resources/en-us/i/a/l_Sweetheart_Bouquet_E504_w.jpg",
                                             :electronics => "http://buybigbang.com/wp-content/uploads/2013/10/gta51.jpg"}},
                                       {:under_100 =>
                                               {:sports => "http://cdn2.bigcommerce.com/server1100/37bd3/products/34/images/185/nflftbl2__39130.1337626940.320.320.jpg?c=2",
                                               :nature => "http://guideimg.alibaba.com/images/shop/2015/07/30/31/giant-lighted-ecosystem-ant-habitat-with-free-certificate-for-25-live-ants-1-tube-of-ants_6840031.jpeg",
                                               :music => "http://store.sony.com/SNYNA_27/pimg/pSNYNA-NWZE385BLK_main_v500.png",
                                               :art => "http://ecx.images-amazon.com/images/I/51BHVKaXseL._AC_UL320_SR240,320_.jpg",
                                               :romantic_gifts => "http://www.giftsforyounow.com/images/products/ValentinesDay/His--Hers-Personalized-Pillowcase-set_83020870aLM.jpg",
                                               :electronics => "http://oyster.ignimgs.com/mediawiki/apis.ign.com/star-wars-episode-7/thumb/2/21/STAR-WARS-Battlefront-Deluxe-Edition-PlayStation-4.jpg/468px-STAR-WARS-Battlefront-Deluxe-Edition-PlayStation-4.jpg"}},
                                       {:over_100 =>
                                               {:sports => "http://ecx.images-amazon.com/images/I/51e4s724TbL._SX355_.jpg",
                                               :nature => "http://www.hometrainingtools.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/i/mi-dscpmeg.jpg",
                                               :music => "http://www.billboard.com/files/media/2014-oprah-favorite-things-beats-billboard-510.jpg",
                                               :art => "http://parkwestgallery.com/wp-content/uploads/2012/12/art-basel-miami-beach-britto-porsche.jpg",
                                               :romantic_gifts => [],
                                               :electronics => "http://pisces.bbystatic.com/image2/BestBuy_US/images/products/4380/4380083_sd.jpg;canvasHeight=500;canvasWidth=500"}}},
                             {:blood_relative =>
                                       {:under_50 =>
                                             {:sports => "http://ecx.images-amazon.com/images/I/812WyxHZm6L._SX425_.jpg",
                                             :nature => "Amscope Metal Body Kids Student Beginner Biological Microscope Kit",
                                             :music => "http://ecx.images-amazon.com/images/I/91KLFz-tGjL._SX355_.jpg",
                                             :art => [],
                                             :electronics => "http://buybigbang.com/wp-content/uploads/2013/10/gta51.jpg"}},
                                       {:under_100 =>
                                               {:sports => "http://cdn2.bigcommerce.com/server1100/37bd3/products/34/images/185/nflftbl2__39130.1337626940.320.320.jpg?c=2",
                                               :nature => "http://guideimg.alibaba.com/images/shop/2015/07/30/31/giant-lighted-ecosystem-ant-habitat-with-free-certificate-for-25-live-ants-1-tube-of-ants_6840031.jpeg",
                                               :music => "http://store.sony.com/SNYNA_27/pimg/pSNYNA-NWZE385BLK_main_v500.png",
                                               :art => "http://ecx.images-amazon.com/images/I/51BHVKaXseL._AC_UL320_SR240,320_.jpg",
                                               :electronics => "http://oyster.ignimgs.com/mediawiki/apis.ign.com/star-wars-episode-7/thumb/2/21/STAR-WARS-Battlefront-Deluxe-Edition-PlayStation-4.jpg/468px-STAR-WARS-Battlefront-Deluxe-Edition-PlayStation-4.jpg"}},
                                       {:over_100 =>
                                               {:sports => "http://ecx.images-amazon.com/images/I/51e4s724TbL._SX355_.jpg",
                                               :nature => "http://www.hometrainingtools.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/i/mi-dscpmeg.jpg",
                                               :music => "http://www.billboard.com/files/media/2014-oprah-favorite-things-beats-billboard-510.jpg",
                                               :art => "http://parkwestgallery.com/wp-content/uploads/2012/12/art-basel-miami-beach-britto-porsche.jpg",
                                               :electronics => "http://pisces.bbystatic.com/image2/BestBuy_US/images/products/4380/4380083_sd.jpg;canvasHeight=500;canvasWidth=500"}}},
                              {:extended_family =>
                                       {:under_50 =>
                                             {:sports => "http://ecx.images-amazon.com/images/I/812WyxHZm6L._SX425_.jpg",
                                             :nature => "Amscope Metal Body Kids Student Beginner Biological Microscope Kit",
                                             :music => [],
                                             :art => "http://ecx.images-amazon.com/images/I/91KLFz-tGjL._SX355_.jpg",
                                             :electronics => "http://buybigbang.com/wp-content/uploads/2013/10/gta51.jpg"}},
                                       {:under_100 =>
                                               {:sports => "http://cdn2.bigcommerce.com/server1100/37bd3/products/34/images/185/nflftbl2__39130.1337626940.320.320.jpg?c=2",
                                               :nature => "http://guideimg.alibaba.com/images/shop/2015/07/30/31/giant-lighted-ecosystem-ant-habitat-with-free-certificate-for-25-live-ants-1-tube-of-ants_6840031.jpeg",
                                               :music => "http://store.sony.com/SNYNA_27/pimg/pSNYNA-NWZE385BLK_main_v500.png",
                                               :art => "http://ecx.images-amazon.com/images/I/51BHVKaXseL._AC_UL320_SR240,320_.jpg",
                                               :electronics => "http://oyster.ignimgs.com/mediawiki/apis.ign.com/star-wars-episode-7/thumb/2/21/STAR-WARS-Battlefront-Deluxe-Edition-PlayStation-4.jpg/468px-STAR-WARS-Battlefront-Deluxe-Edition-PlayStation-4.jpg"}}
                                       {:over_100 =>
                                               {:sports => "http://ecx.images-amazon.com/images/I/51e4s724TbL._SX355_.jpg",
                                               :nature => "http://www.hometrainingtools.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/i/mi-dscpmeg.jpg",
                                               :music => "http://www.billboard.com/files/media/2014-oprah-favorite-things-beats-billboard-510.jpg",
                                               :art => "http://parkwestgallery.com/wp-content/uploads/2012/12/art-basel-miami-beach-britto-porsche.jpg",
                                               :electronics => "http://pisces.bbystatic.com/image2/BestBuy_US/images/products/4380/4380083_sd.jpg;canvasHeight=500;canvasWidth=500"}}},
                                 {:friend =>
                                       {:under_50 =>
                                             {:sports => "http://ecx.images-amazon.com/images/I/812WyxHZm6L._SX425_.jpg",
                                             :nature => "Amscope Metal Body Kids Student Beginner Biological Microscope Kit",
                                             :music => [],
                                             :art => "http://ecx.images-amazon.com/images/I/91KLFz-tGjL._SX355_.jpg",
                                             :romantic_gifts => "http://www.giftsforyounow.com/images/products/ValentinesDay/His--Hers-Personalized-Pillowcase-set_83020870aLM.jpg",
                                             :electronics => "http://buybigbang.com/wp-content/uploads/2013/10/gta51.jpg"}},
                                       {:under_100 =>
                                               {:sports => "http://cdn2.bigcommerce.com/server1100/37bd3/products/34/images/185/nflftbl2__39130.1337626940.320.320.jpg?c=2",
                                               :nature => "http://guideimg.alibaba.com/images/shop/2015/07/30/31/giant-lighted-ecosystem-ant-habitat-with-free-certificate-for-25-live-ants-1-tube-of-ants_6840031.jpeg",
                                               :music => "http://store.sony.com/SNYNA_27/pimg/pSNYNA-NWZE385BLK_main_v500.png",
                                               :art => "http://ecx.images-amazon.com/images/I/51BHVKaXseL._AC_UL320_SR240,320_.jpg",
                                               :romantic_gifts => "http://www.giftsforyounow.com/images/products/ValentinesDay/His--Hers-Personalized-Pillowcase-set_83020870aLM.jpg",
                                               :electronics => "http://oyster.ignimgs.com/mediawiki/apis.ign.com/star-wars-episode-7/thumb/2/21/STAR-WARS-Battlefront-Deluxe-Edition-PlayStation-4.jpg/468px-STAR-WARS-Battlefront-Deluxe-Edition-PlayStation-4.jpg"}},
                                       {:over_100 =>
                                               {:sports => "http://ecx.images-amazon.com/images/I/51e4s724TbL._SX355_.jpg",
                                               :nature => "http://www.hometrainingtools.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/i/mi-dscpmeg.jpg",
                                               :music => "http://www.billboard.com/files/media/2014-oprah-favorite-things-beats-billboard-510.jpg",
                                               :art => "http://parkwestgallery.com/wp-content/uploads/2012/12/art-basel-miami-beach-britto-porsche.jpg",
                                               :romantic_gifts => [],
                                               :electronics => "http://pisces.bbystatic.com/image2/BestBuy_US/images/products/4380/4380083_sd.jpg;canvasHeight=500;canvasWidth=500"}}}},
                       {:female =>
                           {:significant_other =>
                                       {:under_50 =>
                                             {:sports => [],
                                             :nature => "Amscope Metal Body Kids Student Beginner Biological Microscope Kit",
                                             :music => "https://img0.etsystatic.com/062/0/8907796/il_570xN.791932066_4hpb.jpg",
                                             :art => "http://ecx.images-amazon.com/images/I/91KLFz-tGjL._SX355_.jpg",
                                             :romantic_gifts => "http://www.giftsforyounow.com/images/products/ValentinesDay/His--Hers-Personalized-Pillowcase-set_83020870aLM.jpg",
                                             :electronics => []}},
                                       {:under_100 =>
                                               {:sports => "thumbs4.ebaystatic.com/d/l225/pict/191668076187_1.jpg",
                                               :nature => "http://guideimg.alibaba.com/images/shop/2015/07/30/31/giant-lighted-ecosystem-ant-habitat-with-free-certificate-for-25-live-ants-1-tube-of-ants_6840031.jpeg",
                                               :music => "http://store.sony.com/SNYNA_27/pimg/pSNYNA-NWZE385BLK_main_v500.png",
                                               :art => "http://ecx.images-amazon.com/images/I/51BHVKaXseL._AC_UL320_SR240,320_.jpg",
                                               :romantic_gifts => "http://www.giftsforyounow.com/images/products/ValentinesDay/His--Hers-Personalized-Pillowcase-set_83020870aLM.jpg",
                                               :electronics => []}},
                                       {:over_100 =>
                                               {:sports => "http://ecx.images-amazon.com/images/I/51e4s724TbL._SX355_.jpg",
                                               :nature => "http://www.hometrainingtools.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/i/mi-dscpmeg.jpg",
                                               :music => "http://www.billboard.com/files/media/2014-oprah-favorite-things-beats-billboard-510.jpg",
                                               :art => "http://parkwestgallery.com/wp-content/uploads/2012/12/art-basel-miami-beach-britto-porsche.jpg",
                                               :romantic_gifts => [],
                                               :electronics => "http://pisces.bbystatic.com/image2/BestBuy_US/images/products/4380/4380083_sd.jpg;canvasHeight=500;canvasWidth=500"}}},
                             {:blood_relative =>
                                       {:under_50 =>
                                             {:sports => ,
                                             :nature => "Amscope Metal Body Kids Student Beginner Biological Microscope Kit",
                                             :music => [],
                                             :art => "http://ecx.images-amazon.com/images/I/91KLFz-tGjL._SX355_.jpg",
                                             :electronics => []}},
                                       {:under_100 =>
                                               {:sports => "thumbs4.ebaystatic.com/d/l225/pict/191668076187_1.jpg",
                                               :nature => "http://guideimg.alibaba.com/images/shop/2015/07/30/31/giant-lighted-ecosystem-ant-habitat-with-free-certificate-for-25-live-ants-1-tube-of-ants_6840031.jpeg",
                                               :music => "http://ecx.images-amazon.com/images/I/31spWtoMRbL.jpg",
                                               :art => "http://ecx.images-amazon.com/images/I/51BHVKaXseL._AC_UL320_SR240,320_.jpg",
                                               :electronics => []}},
                                       {:over_100 =>
                                               {:sports => "http://ecx.images-amazon.com/images/I/51e4s724TbL._SX355_.jpg",
                                               :nature => "http://www.hometrainingtools.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/i/mi-dscpmeg.jpg",
                                               :music => "http://www.billboard.com/files/media/2014-oprah-favorite-things-beats-billboard-510.jpg",
                                               :art => "http://parkwestgallery.com/wp-content/uploads/2012/12/art-basel-miami-beach-britto-porsche.jpg",
                                               :electronics => "http://pisces.bbystatic.com/image2/BestBuy_US/images/products/4380/4380083_sd.jpg;canvasHeight=500;canvasWidth=500"}}},
                              {:extended_family =>
                                       {:under_50 =>
                                             {:sports => [],
                                             :nature => "Amscope Metal Body Kids Student Beginner Biological Microscope Kit",
                                             :music => [],
                                             :art => "http://ecx.images-amazon.com/images/I/91KLFz-tGjL._SX355_.jpg",
                                             :electronics => []}},
                                       {:under_100 =>
                                               {:sports => "thumbs4.ebaystatic.com/d/l225/pict/191668076187_1.jpg",
                                               :nature => "http://guideimg.alibaba.com/images/shop/2015/07/30/31/giant-lighted-ecosystem-ant-habitat-with-free-certificate-for-25-live-ants-1-tube-of-ants_6840031.jpeg",
                                               :music => "http://ecx.images-amazon.com/images/I/31spWtoMRbL.jpg",
                                               :art => "http://ecx.images-amazon.com/images/I/51BHVKaXseL._AC_UL320_SR240,320_.jpg",
                                               :electronics => []}},
                                       {:over_100 =>
                                               {:sports => "http://ecx.images-amazon.com/images/I/51e4s724TbL._SX355_.jpg",
                                               :nature => "http://www.hometrainingtools.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/i/mi-dscpmeg.jpg",
                                               :music => "http://www.billboard.com/files/media/2014-oprah-favorite-things-beats-billboard-510.jpg",
                                               :art => "http://parkwestgallery.com/wp-content/uploads/2012/12/art-basel-miami-beach-britto-porsche.jpg",
                                               :electronics => "http://pisces.bbystatic.com/image2/BestBuy_US/images/products/4380/4380083_sd.jpg;canvasHeight=500;canvasWidth=500"}}},
                                 {:friend =>
                                       {:under_50 =>
                                             {:sports => [],
                                             :nature => "Amscope Metal Body Kids Student Beginner Biological Microscope Kit",
                                             :music => [],
                                             :art => "http://ecx.images-amazon.com/images/I/91KLFz-tGjL._SX355_.jpg",
                                             :romantic_gifts => "http://www.giftsforyounow.com/images/products/ValentinesDay/His--Hers-Personalized-Pillowcase-set_83020870aLM.jpg",
                                             :electronics => []}},
                                       {:under_100 =>
                                               {:sports => "thumbs4.ebaystatic.com/d/l225/pict/191668076187_1.jpg",
                                               :nature => "http://guideimg.alibaba.com/images/shop/2015/07/30/31/giant-lighted-ecosystem-ant-habitat-with-free-certificate-for-25-live-ants-1-tube-of-ants_6840031.jpeg",
                                               :music => "http://ecx.images-amazon.com/images/I/31spWtoMRbL.jpg",
                                               :art => "http://ecx.images-amazon.com/images/I/51BHVKaXseL._AC_UL320_SR240,320_.jpg",
                                               :romantic_gifts => "http://www.giftsforyounow.com/images/products/ValentinesDay/His--Hers-Personalized-Pillowcase-set_83020870aLM.jpg",
                                               :electronics => []}},
                                       {:over_100 =>
                                               {:sports => "http://ecx.images-amazon.com/images/I/51e4s724TbL._SX355_.jpg",
                                               :nature => "http://www.hometrainingtools.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/i/mi-dscpmeg.jpg",
                                               :music => "http://www.billboard.com/files/media/2014-oprah-favorite-things-beats-billboard-510.jpg",
                                               :art => "http://parkwestgallery.com/wp-content/uploads/2012/12/art-basel-miami-beach-britto-porsche.jpg",
                                               :romantic_gifts => [],
                                               :electronics => "http://pisces.bbystatic.com/image2/BestBuy_US/images/products/4380/4380083_sd.jpg;canvasHeight=500;canvasWidth=500"}}}}},
{:adult => {:male =>
                           {:significant_other =>
                                       {:under_50 =>
                                             {:sports => "http://a66c7b.medialib.glogster.com/media/ea/ea67d7ae0b54815d7c9abe8b900d6ff92dcdf50ed0799946ee26f8304cc36a4e/hacky.jpg",
                                             :nature => "https://uniquephoto-weblinc.netdna-ssl.com/images/products/processed/EKC2548.zoom.a.jpg",
                                             :music => "https://eagerlyiwishthemorrow.files.wordpress.com/2014/06/fifties-rock-and-roll-record-coasters-deco338.jpg",
                                             :art => "http://www.belloflostsouls.net/wp-content/uploads/2014/08/paint-cans.png",
                                             :romantic_gifts => "http://7-themes.com/data_images/out/5/6785321-cute-teddy-bear.jpg",
                                             :electronics => "https://uniquephoto-weblinc.netdna-ssl.com/images/products/processed/EKC2548.zoom.a.jpg",
                                             :house_gifts => "http://images.luuux.com/0000EFA7D0EDB69D747C0A9E55BF9D78/middle/Lady-Fuzzy-Socks.jpg"}},
                                       {:under_100 =>
                                               {:sports => "http://www.hittersparadise.com/images/inventory/bats/bats_softball_s300_2014_lrg.gif",
                                               :nature => "https://www.google.com/search?q=binoculars&espv=2&biw=763&bih=616&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAmoVChMIxIvHlv3LxwIVhBo-Ch3XWwgi#imgrc=RbADYwEC7BGqwM%3A",
                                               :music => "http://canada.jamaudio.com/media/catalog/product/cache/155/image/1000x800/9df78eab33525d08d6e5fb8d27136e95/j/a/jam-transit-headphone-angle-a-red-fnl_1_1_1.jpg",
                                               :art => "http://paintingforsale.me/images/paintings/original/original-landscape-24585.jpg",
                                               :romantic_gifts => "http://www.primermagazine.com/wp-content/uploads/2011/12/Champagne/Champagne_bg.jpg",
                                               :electronics => "https://images-na.ssl-images-amazon.com/images/G/01/videogames/detail-page/vg.consoles.01.lg.jpg"},
                                               :house_gifts => "http://3.bp.blogspot.com/-tzIQIDD-teU/UpZgipQ7ykI/AAAAAAAAa5I/tKnSd9B8nUg/s1600/marshall_amp_mugrock_mug_rocker_guitar_cool_gifts_for_guys.jpg"}},
                                       {:over_100 =>
                                               {:sports => "http://www.grandstandsports.com/images/30898.jpg",
                                               :nature => "http://www.rei.com/media/oo/093ce4ac-cf2e-4562-b411-56d76b8519d4.jpg",
                                               :music => "http://dri1.img.digitalrivercontent.net/Storefront/Company/msintl/images/English/en_INTL_BEATS_by_Dre_Pill_Red_DHF-01155/en_L_INTL_BEATS_by_Dre_Pill_Red_DHF-01155_RM2_mnco.jpg",
                                               :art => "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg/687px-Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg",
                                               :romantic_gifts => "http://www.toxel.com/wp-content/uploads/2010/02/fireplace06.jpg",
                                               :electronics => "http://s3.amazonaws.com/ClubExpressClubFiles/748044/graphics/Mac_1624891939.jpg",
                                               :house_gifts => "http://supreme-auctions.com/wp-content/uploads/2015/02/Houston-Tx-Mansion-For-Sale.jpg"}}},
                             {:blood_relative =>
                                       {:under_50 =>
                                             {:sports => "http://a66c7b.medialib.glogster.com/media/ea/ea67d7ae0b54815d7c9abe8b900d6ff92dcdf50ed0799946ee26f8304cc36a4e/hacky.jpg",
                                             :nature => "https://uniquephoto-weblinc.netdna-ssl.com/images/products/processed/EKC2548.zoom.a.jpg",
                                             :music => "https://eagerlyiwishthemorrow.files.wordpress.com/2014/06/fifties-rock-and-roll-record-coasters-deco338.jpg",
                                             :art => "http://www.belloflostsouls.net/wp-content/uploads/2014/08/paint-cans.png",
                                             :electronics => "https://uniquephoto-weblinc.netdna-ssl.com/images/products/processed/EKC2548.zoom.a.jpg",
                                             :house_gifts => "http://images.luuux.com/0000EFA7D0EDB69D747C0A9E55BF9D78/middle/Lady-Fuzzy-Socks.jpg"}},
                                       {:under_100 =>
                                               {:sports => "http://www.hittersparadise.com/images/inventory/bats/bats_softball_s300_2014_lrg.gif",
                                               :nature => "https://www.google.com/search?q=binoculars&espv=2&biw=763&bih=616&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAmoVChMIxIvHlv3LxwIVhBo-Ch3XWwgi#imgrc=RbADYwEC7BGqwM%3A",
                                               :music => "http://canada.jamaudio.com/media/catalog/product/cache/155/image/1000x800/9df78eab33525d08d6e5fb8d27136e95/j/a/jam-transit-headphone-angle-a-red-fnl_1_1_1.jpg",
                                               :art => "http://paintingforsale.me/images/paintings/original/original-landscape-24585.jpg",
                                               :electronics => "https://images-na.ssl-images-amazon.com/images/G/01/videogames/detail-page/vg.consoles.01.lg.jpg",
                                               :house_gifts => "http://3.bp.blogspot.com/-tzIQIDD-teU/UpZgipQ7ykI/AAAAAAAAa5I/tKnSd9B8nUg/s1600/marshall_amp_mugrock_mug_rocker_guitar_cool_gifts_for_guys.jpg"}},
                                       {:over_100 =>
                                               {:sports => "http://www.grandstandsports.com/images/30898.jpg",
                                               :nature => "http://www.rei.com/media/oo/093ce4ac-cf2e-4562-b411-56d76b8519d4.jpg",
                                               :music => "http://dri1.img.digitalrivercontent.net/Storefront/Company/msintl/images/English/en_INTL_BEATS_by_Dre_Pill_Red_DHF-01155/en_L_INTL_BEATS_by_Dre_Pill_Red_DHF-01155_RM2_mnco.jpg",
                                               :art => "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg/687px-Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg",
                                               :electronics => "http://s3.amazonaws.com/ClubExpressClubFiles/748044/graphics/Mac_1624891939.jpg",
                                               :house_gifts => "http://supreme-auctions.com/wp-content/uploads/2015/02/Houston-Tx-Mansion-For-Sale.jpg"}}},
                              {:extended_family =>
                                       {:under_50 =>
                                             {:sports => "http://a66c7b.medialib.glogster.com/media/ea/ea67d7ae0b54815d7c9abe8b900d6ff92dcdf50ed0799946ee26f8304cc36a4e/hacky.jpg",
                                             :nature => "https://uniquephoto-weblinc.netdna-ssl.com/images/products/processed/EKC2548.zoom.a.jpg",
                                             :music => "https://eagerlyiwishthemorrow.files.wordpress.com/2014/06/fifties-rock-and-roll-record-coasters-deco338.jpg",
                                             :art => "http://www.belloflostsouls.net/wp-content/uploads/2014/08/paint-cans.png",
                                             :electronics => "https://uniquephoto-weblinc.netdna-ssl.com/images/products/processed/EKC2548.zoom.a.jpg",
                                             :house_gifts => "http://images.luuux.com/0000EFA7D0EDB69D747C0A9E55BF9D78/middle/Lady-Fuzzy-Socks.jpg"}},
                                       {:under_100 =>
                                               {:sports => "http://www.hittersparadise.com/images/inventory/bats/bats_softball_s300_2014_lrg.gif",
                                               :nature => "https://www.google.com/search?q=binoculars&espv=2&biw=763&bih=616&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAmoVChMIxIvHlv3LxwIVhBo-Ch3XWwgi#imgrc=RbADYwEC7BGqwM%3A",
                                               :music => "http://canada.jamaudio.com/media/catalog/product/cache/155/image/1000x800/9df78eab33525d08d6e5fb8d27136e95/j/a/jam-transit-headphone-angle-a-red-fnl_1_1_1.jpg",
                                               :art => "http://paintingforsale.me/images/paintings/original/original-landscape-24585.jpg",
                                               :electronics => "https://images-na.ssl-images-amazon.com/images/G/01/videogames/detail-page/vg.consoles.01.lg.jpg",
                                               :house_gifts => "http://3.bp.blogspot.com/-tzIQIDD-teU/UpZgipQ7ykI/AAAAAAAAa5I/tKnSd9B8nUg/s1600/marshall_amp_mugrock_mug_rocker_guitar_cool_gifts_for_guys.jpg"}},
                                       {:over_100 =>
                                               {:sports => "http://www.grandstandsports.com/images/30898.jpg",
                                               :nature => "http://www.rei.com/media/oo/093ce4ac-cf2e-4562-b411-56d76b8519d4.jpg",
                                               :music => "http://dri1.img.digitalrivercontent.net/Storefront/Company/msintl/images/English/en_INTL_BEATS_by_Dre_Pill_Red_DHF-01155/en_L_INTL_BEATS_by_Dre_Pill_Red_DHF-01155_RM2_mnco.jpg",
                                               :art => "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg/687px-Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg",
                                               :electronics => "http://s3.amazonaws.com/ClubExpressClubFiles/748044/graphics/Mac_1624891939.jpg",
                                               :house_gifts => "http://supreme-auctions.com/wp-content/uploads/2015/02/Houston-Tx-Mansion-For-Sale.jpg"}}},
                                 {:friend =>
                                       {:under_50 =>
                                             {:sports => "http://a66c7b.medialib.glogster.com/media/ea/ea67d7ae0b54815d7c9abe8b900d6ff92dcdf50ed0799946ee26f8304cc36a4e/hacky.jpg",
                                             :nature => "https://uniquephoto-weblinc.netdna-ssl.com/images/products/processed/EKC2548.zoom.a.jpg",
                                             :music => "https://eagerlyiwishthemorrow.files.wordpress.com/2014/06/fifties-rock-and-roll-record-coasters-deco338.jpg",
                                             :art => "http://www.belloflostsouls.net/wp-content/uploads/2014/08/paint-cans.png",
                                             :romantic_gifts => "http://7-themes.com/data_images/out/5/6785321-cute-teddy-bear.jpg",
                                             :electronics => "https://uniquephoto-weblinc.netdna-ssl.com/images/products/processed/EKC2548.zoom.a.jpg",
                                             :house_gifts => "http://images.luuux.com/0000EFA7D0EDB69D747C0A9E55BF9D78/middle/Lady-Fuzzy-Socks.jpg"}},
                                       {:under_100 =>
                                               {:sports => "http://www.hittersparadise.com/images/inventory/bats/bats_softball_s300_2014_lrg.gif",
                                               :nature => "https://www.google.com/search?q=binoculars&espv=2&biw=763&bih=616&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAmoVChMIxIvHlv3LxwIVhBo-Ch3XWwgi#imgrc=RbADYwEC7BGqwM%3A",
                                               :music => "http://canada.jamaudio.com/media/catalog/product/cache/155/image/1000x800/9df78eab33525d08d6e5fb8d27136e95/j/a/jam-transit-headphone-angle-a-red-fnl_1_1_1.jpg",
                                               :art => "http://paintingforsale.me/images/paintings/original/original-landscape-24585.jpg",
                                               :romantic_gifts => "http://www.primermagazine.com/wp-content/uploads/2011/12/Champagne/Champagne_bg.jpg",
                                               :electronics => "https://images-na.ssl-images-amazon.com/images/G/01/videogames/detail-page/vg.consoles.01.lg.jpg",
                                               :house_gifts => "http://3.bp.blogspot.com/-tzIQIDD-teU/UpZgipQ7ykI/AAAAAAAAa5I/tKnSd9B8nUg/s1600/marshall_amp_mugrock_mug_rocker_guitar_cool_gifts_for_guys.jpg"}},
                                       {:over_100 =>
                                               {:sports => "http://www.grandstandsports.com/images/30898.jpg",
                                               :nature => "http://www.rei.com/media/oo/093ce4ac-cf2e-4562-b411-56d76b8519d4.jpg",
                                               :music => "http://dri1.img.digitalrivercontent.net/Storefront/Company/msintl/images/English/en_INTL_BEATS_by_Dre_Pill_Red_DHF-01155/en_L_INTL_BEATS_by_Dre_Pill_Red_DHF-01155_RM2_mnco.jpg",
                                               :art => "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg/687px-Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg",
                                               :romantic_gifts => "http://www.toxel.com/wp-content/uploads/2010/02/fireplace06.jpg",
                                               :electronics => "http://s3.amazonaws.com/ClubExpressClubFiles/748044/graphics/Mac_1624891939.jpg",
                                               :house_gifts => "http://supreme-auctions.com/wp-content/uploads/2015/02/Houston-Tx-Mansion-For-Sale.jpg"}}}},
#                        {:female =>
#                            {:significant_other =>
#                                        {:under_50 =>
#                                              {:sports => []},
#                                              {:nature => []},
#                                              {:music => []},
#                                              {:art => []},
#                                              {:romantic_gifts => []},
#                                              {:electronics => []},
#                                              {:house_gifts => []}},
#                                        {:under_100 =>
#                                                {:sports => []},
#                                                {:nature => []},
#                                                {:music => []},
#                                                {:art => []},
#                                                {:romantic_gifts => []},
#                                                {:electronics => []},
#                                                {:house_gifts => []}},
#                                        {:over_100 =>
#                                                {:sports => []},
#                                                {:nature => []},
#                                                {:music => []},
#                                                {:art => []},
#                                                {:romantic_gifts => []},
#                                                {:electronics => []},
#                                                {:house_gifts => []}}},
#                              {:blood_relative =>
#                                        {:under_50 =>
#                                              {:sports => []},
#                                              {:nature => []},
#                                              {:music => []},
#                                              {:art => []},
#                                              {:electronics => []},
#                                              {:house_gifts => []}},
#                                        {:under_100 =>
#                                                {:sports => []},
#                                                {:nature => []},
#                                                {:music => []},
#                                                {:art => []},
#                                                {:electronics => []},
#                                                {:house_gifts => []}},
#                                        {:over_100 =>
#                                                {:sports => []},
#                                                {:nature => []},
#                                                {:music => []},
#                                                {:art => []},
#                                                {:electronics => []},
#                                                {:house_gifts => []}}},
#                               {:extended_family =>
#                                        {:under_50 =>
#                                              {:sports => []},
#                                              {:nature => []},
#                                              {:music => []},
#                                              {:art => []},
#                                              {:electronics => []},
#                                              {:house_gifts => []}},
#                                        {:under_100 =>
#                                                {:sports => []},
#                                                {:nature => []},
#                                                {:music => []},
#                                                {:art => []},
#                                                {:electronics => []},
#                                                {:house_gifts => []}},
#                                        {:over_100 =>
#                                                {:sports => []},
#                                                {:nature => []},
#                                                {:music => []},
#                                                {:art => []},
#                                                {:electronics => []},
#                                                {:house_gifts => []}}},
#                                  {:friend =>
#                                        {:under_50 =>
#                                              {:sports => []},
#                                              {:nature => []},
#                                              {:music => []},
#                                              {:art => []},
#                                              {:romantic_gifts => []},
#                                              {:electronics => []},
#                                              {:house_gifts => []}},
#                                        {:under_100 =>
#                                                {:sports => []},
#                                                {:nature => []},
#                                                {:music => []},
#                                                {:art => []},
#                                                {:romantic_gifts => []},
#                                                {:electronics => []},
#                                                {:house_gifts => []}},
#                                        {:over_100 =>
#                                                {:sports => []},
#                                                {:nature => []},
#                                                {:music => []},
#                                                {:art => []},
#                                                {:romantic_gifts => []},
#                                                {:electronics => []},
#                                                {:house_gifts => []}}}}},

  end
end